//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LettreCooperation.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LC
    {
        public int id_lc { get; set; }
        public string chemin_lc { get; set; }
        public System.DateTime date_lc { get; set; }
        public Nullable<System.DateTime> date_debut { get; set; }
        public Nullable<System.DateTime> date_fin { get; set; }
        public int id_client { get; set; }
        public int id_modele { get; set; }
        public string nom_lc { get; set; }
        public Nullable<int> id_etat { get; set; }
        public Nullable<int> id_utilisateur { get; set; }
        public Nullable<int> id_signataire { get; set; }
        public string millesime { get; set; }
        public Nullable<System.DateTime> exercice_debut { get; set; }
        public Nullable<System.DateTime> exercice_fin { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Etat Etat { get; set; }
        public virtual Modele Modele { get; set; }
        public virtual Utilisateur Utilisateur { get; set; }
        public virtual Utilisateur Utilisateur1 { get; set; }
    }
}
